### PR TITLE
Some improvements to the website

### PR DESCRIPTION
**Pull request by luzeagithub**
First, i added a new FAQ entry for those (2) builds:
image
(+ de-de translation)

Second, I changed the "rings" to "channels" on selectlang.php:
image
(+ de-de translation)

Everything was tested, it works.

### CODE REVIEW

**Review by awuctl — CHANGES_REQUESTED** [review]
A bit too much was changed for a single commit.

The FAQ entry has to be slightly adjusted.
You can add information that it is **generally** the case; there were some builds where that wasn't true, for example:
https://github.com/uup-dump/fileinfo/commit/a07fb7294bf5ec0223741c02d2bf8d9f58f060a6
(Before the (2) became a thing, updates with duplicate names were deleted)

**Comment by awuctl** [comment]
Here's the API commit that added the (2) magic.
https://github.com/uup-dump/api/commit/71ee499b4afa43e68dc3ad8052b6c3dc11072891

**Comment by luzeagithub** [comment]
adjusted the FAQ entries

**Comment by awuctl** [comment]
looks alright

**Pull request merged**
